### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by PLUCS2** [cmwinner89/TrailMix#2]
- [x] Signup for All Trails does not ask for city or state info 
- [x] Trails should have a `name` 
- [x] The description appears to be optional for Trails (meaning that null would be acceptable) 
- [x] What is `route_type` on the Trails table? Is it a specific collection of available options? If yes - specify that.
- [x] You should add a `latitude` and `longitude` to the Trails table to be able to add them to maps via the google maps api
- [x] What is `park_type` on the Parks table? If these are specific - please specify what the options there are 

This looks good! Let me know if you have any questions

**Comment by cmwinner89** [comment]
I just notice that in the profile page it has the city and state.  Where would I implement that in then?
